# Generated by Django 5.0 on 2024-12-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('num_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('numero', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=255)),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
